from selenium.webdriver.common.by import By


class RegisterPageLocators:
    FIRSTNAME = (By.CSS_SELECTOR, '#input-firstname')
    FIRST_NAME_LABEL = (By.CSS_SELECTOR, '#account > div:nth-child(3) > label')
    FIRST_NAME_ERRORMESSAGE = (By.CSS_SELECTOR, '#account > div:nth-child(3) > div > div')
    LASTNAME = (By.XPATH, '//*[@id="input-lastname"]')
    LASTNAME_LABEL = (By.CSS_SELECTOR, '#account > div:nth-child(4) > label')
    LASTNAME_ERRORMESSAGE = (By.CSS_SELECTOR, '#account > div:nth-child(4) > div > div')
    EMAIL = (By.XPATH, '//*[@id="input-email"]')
    EMAIL_LABEL = (By.CSS_SELECTOR, '#account > div:nth-child(5) > label')
    EMAIL_ERRORMESSAGE = (By.CSS_SELECTOR, '//*[@id="input-email"]')
    TELEPHONE = (By.XPATH, '//*[@id="input-telephone"]')
    TELEPHONE = (By.CSS_SELECTOR, '//*[@id="input-telephone"]')
    TELEPHONE_ERRORMESSAGE = (By.CSS_SELECTOR, '//*[@id="input-telephone"]')
    ADDRESS1 = (By.XPATH, '//*[@id="input-address-1"]')
    ADDRESS1 = (By.CSS_SELECTOR, '//*[@id="input-address-1"]')
    ADDRESS1_ERRORMESSAGE = (By.CSS_SELECTOR, '//*[@id="input-address-1"]')
    CITY = (By.XPATH, '//*[@id="input-city"]')
    CITY = (By.CSS_SELECTOR, '//*[@id="input-city"]')
    CITY_ERRORMESSAGE = (By.CSS_SELECTOR, '//*[@id="input-city"]')
    POSTCODE = (By.XPATH, '//*[@id="input-postcode"]')
    POSTCODE = (By.CSS_SELECTOR, '//*[@id="input-postcode"]')
    POSTCODE_ERRORMESSAGE = (By.CSS_SELECTOR, '//*[@id="input-postcode"]')
    DROPDOWN_REGION_STATE = (By.CSS_SELECTOR, '#input-zone')
    DROPDOWN_REGION_STATE = (By.CSS_SELECTOR, '#input-zone')
    DROPDOWN_REGION_STATE_ERRORMESSAGE = (By.CSS_SELECTOR, '#input-zone')
    COUNTRY = (By.XPATH, '//*[@id="input-country"]')
    COUNTRY = (By.CSS_SELECTOR, '//*[@id="input-country"]')
    COUNTRY_ERRORMESSAGE = (By.CSS_SELECTOR, '//*[@id="input-country"]')
    COUNTRYOPTION = (By.XPATH, '//*[@id="input-country"]/option[2]')
    REGION = (By.ID, 'input-zone')
    REGION = (By.CSS_SELECTOR, 'input-zone')
    REGION_ERRORMESSAGE = (By.CSS_SELECTOR, 'input-zone')
    REGIONOPTION = (By.XPATH, '//*[@id="input-zone"]/option[2]')

    REGION_OPTION_Albania = (By.XPATH, '//*[@id="input-zone"]/option[2]')
    PASSWORD = (By.XPATH, '//*[@id="input-password"]')
    PASSWORD = (By.CSS_SELECTOR, '//*[@id="input-password"]')
    PASSWORD_ERRORMESSAGE = (By.CSS_SELECTOR, '//*[@id="input-password"]')
    PASSWORDCONFIRM = (By.XPATH, '//*[@id="input-confirm"]')
    PASSWORDCONFIRM = (By.CSS_SELECTOR, '//*[@id="input-confirm"]')
    PASSWORDCONFIRM_ERRORMESSAGE = (By.CSS_SELECTOR, '//*[@id="input-confirm"]')
    PRIVACYPOLICYCHECKMARK = (By.XPATH, '//*[@id="content"]/form/div/div/input[1]')
    PRIVACYPOLICYCHECKMARK = (By.CSS_SELECTOR, '//*[@id="content"]/form/div/div/input[1]')
    PRIVACYPOLICYCHECKMARK_ERRORMESSAGE = (By.CSS_SELECTOR, '//*[@id="content"]/form/div/div/input[1]')
    CONTINUEBTN = (By.XPATH, './/input[@class="btn btn-primary"]')
    SUCCESSMESSAGE = (By.XPATH, '//*[@id="content"]/h1')

